### ISSUE TITLE
minor UI nit: extra pixel line?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/api.dart.dev#52]
I just noticed a minor thing in the UI on my chromebook. THis only shows up when the window is maximized vertically.

I can see a line, practically just a 1px width, between the top-banner and the sub-banner. Here is a screenshot:

![screenshot 2015-11-17 at 9 29 50 am](https://cloud.githubusercontent.com/assets/2049220/11219214/19a3a7be-8d0e-11e5-9994-c088450996fc.png)

Then, when scrolling down and you make the subbanner disappear, the pixel line is visible on the top, above the top-banner. See for example that in this screenshot some of the letters are visible behind the banner (between the grey bookmarks bar and the Dart SDK banner:

![screenshot 2015-11-17 at 9 30 01 am](https://cloud.githubusercontent.com/assets/2049220/11219213/199f38a0-8d0e-11e5-8c83-c6ecc899e5e5.png)

Version information: Google Chrome 46.0.2490.82 (Official Build) (64-bit)

**Comment by athomas** [comment]
Can't reproduce.
