### ISSUE TITLE
Add a Search URL

### ISSUE THREAD

**Issue by natebosch** [dart-lang/api.dart.dev#67]
The search box is backed by JS magic and I don't ever see it hit a URL to do the searching.
I'd like to add a search engine shortcut to chrome but I'd need to be able to build a query URL and I can't find a way to do that.

**Comment by athomas** [comment]
Should be possible now:
https://github.com/dart-lang/api.dart.dev/issues/90#issuecomment-2482391297

But to make it discoverable, dartdoc output would need to change which is a different issue that should be filed in dart-lang/dartdoc.
