### ISSUE TITLE
api.dartlang.org does not have a "certificate transparency" proof in its certificate

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/api.dart.dev#70]
We need to have a certificate with certificate transparency at our next update or Chrome will put interstitals in accesses to api.dartlang.org.

**Comment by jcollins-g** [comment]
The warning email from Google App Engine says that old certificates are fine, but  api.dartlang.org's current certificate runs out June 17.

**Comment by jonasfj** [comment]
Google Cloud is now handling automatic renewal of certificates for us, I'm think these also include CT.
