### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/api.dart.dev#74]
If you look at dart.dev, you can see that it has the new, less green logo. I think this site should use that new logo, too.

![Screenshot_20200122-161811](https://user-images.githubusercontent.com/2164483/72946183-01bcd380-3d33-11ea-93f3-bdb1d3441b0b.png)

**Comment by kwalrath** [comment]
Ah, interestingly it's only the old releases that have the old color — presumably because they haven't been regenerated. If you go to https://api.dart.dev, then the favicon is fine.

**Comment by athomas** [comment]
Won't fix the old stable versions, this would mean updating all the static assets which is not worth it given that few people will look at the ancient versions.
