### ISSUE TITLE
Enable brotli compression as an option for content encoding

### ISSUE THREAD

**Issue by parlough** [dart-lang/api.dart.dev#84]
Currently only gzip seems to be supported, but based off my observations hosting the SDK docs on Firebase, the extra compression from [brotli](https://github.com/google/brotli) is not bad. api.flutter.dev also supports brotli already.

**Comment by athomas** [comment]
The new site seems to support this:
```
$ curl --head --header 'Accept-Encoding: br' --silent https://api.dart.dev/ | grep content-encoding
x-goog-stored-content-encoding: identity
content-encoding: br
```
