### ISSUE TITLE
Could not find a command named "doc".

### ISSUE THREAD

**Issue by evanholt1** [dart-lang/api.dart.dev#85]
Greetings!

I know this may be quite trivial,, but when following this guide:
https://dart.dev/tools/dart-doc 
to generate dartdoc for my flutter app,
what i get on the terminal when running `dart doc .` 
from the root directory of my flutter app 
is just `Could not find a command named "doc".`

my dart version is 
`Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "linux_x64"`,
and i have ran `dart pub get` successfully on the project beforehand.

I also did install and globally activate 
https://pub.dev/packages/dartdoc,
but running `dart doc .` or `dartdoc .` neither work.
running `dart help doc` throws the same command, 
and running `dart help` shows me the available commands, none of which is `doc`.

**Comment by athomas** [comment]
This seems more like a help/support request than a bug report about the api.dart.dev. For support, go to https://dart.dev/community.
