### ISSUE TITLE
Make it easy to navigate across documentation for SDK versions

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/api.dart.dev#86]
In addition to https://github.com/dart-lang/api.dart.dev/issues/53, something else to consider is to make it easy to navigate across versions from within the documentation pages themselves.  That would improve the situation for all existing links in the wild.

IMO, Python's documentation handles this very well.  For example: https://docs.python.org/3/library/subprocess.html

I don't know if that's possible.  I think generated dartdocs are self-contained, so maybe not by dartdoc, but maybe the hosting site can do something special?

**Comment by athomas** [comment]
Unfortunately, the new site's backend can't do this. The load balancer rules can't know what versions exist (or they would have to be updated on every commit which is infeasible). This would have to become a feature of dartdoc itself.
