### ISSUE TITLE
Old docs surface in Google

### ISSUE THREAD

**Issue by Hixie** [dart-lang/api.dart.dev#87]
I Googled for [dart stdin] and the top result was https://api.dart.dev/be/136593/dart-io/Stdin-class.html which is from "Dart SDK 1.15.0-edge.1f76ab9410598fca0f7c7c8c9d650cf006950fb3".

**Comment by kevmoo** [comment]
@Hixie – see [go/api-docs-updates-2022](https://goto.google.com/api-docs-updates-2022)

**Comment by athomas** [comment]
Can't reproduce, top result for me is now https://api.dart.dev/dart-io/Stdin-class.html (latest stable). Possibly improved by the new backend.
