### ISSUE TITLE
Would be nice if https://api.dart.dev/stable/search.html?q=... redirected the search

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/api.dart.dev#90]
### Describe the problem

Now that the Dart API documentation supports query-string searches, I can create a keyword search in my browser so that typing `dart QUERY` is automatically expanded to `https://api.dart.dev/stable/2.19.2/search.html?q=QUERY`.  Yay!

However, I would prefer not to search against a specific version; I'd rather just search the latest stable documentation.

I tried making my keyword search instead expand to https://api.dart.dev/stable/search.html?q=QUERY, but that doesn't work.  Even though removing the version number normally redirects to the latest version for concrete URLs (for example., https://api.dart.dev/stable/dart-async/Future-class.html automatically redirects to https://api.dart.dev/stable/2.19.2/dart-async/Future-class.html), removing the version number from the query URL instead redirects to https://api.dart.dev/stable/2.19.2/index.html.

### Expected fix

https://api.dart.dev/stable/search.html?q=QUERY should redirect to `https://api.dart.dev/stable/LATEST_VERSION/search.html?q=QUERY`.

**Comment by athomas** [comment]
This works on the new site:
https://api.dart.dev/search.html?q=QUERY

For other channels than stable (`main|dev|beta`): 
`https://api.dart.dev/<channel>/latest/search.html?q=QUERY`
