### ISSUE TITLE
dart:js_interop is missing from api.dart.dev

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/api.dart.dev#91]
I checked the `dev` channel (https://api.dart.dev/dev/) to double check and there's no documentation for `dart:js_interop`. This package includes crucial extensions for using `package:web` (https://github.com/dart-lang/web).

**Comment by leonsenft** [comment]
@srujzs

**Comment by srujzs** [comment]
Not sure when changes are available on the website, but whenever that happens, dart:js_interop should now be visible.

**Comment by hankyusa** [comment]
I see it there now. I think this issue can be closed.
