### ISSUE TITLE
Too eagerly redirecting to latest stable index page

### ISSUE THREAD

**Issue by parlough** [dart-lang/api.dart.dev#95]
- If I want to access Dart 3.1.5 API docs, I can use https://api.dart.dev/stable/3.1.5/index.html, but https://api.dart.dev/stable/3.1.5 doesn't work.
- If I want to access the `index.json` (search index) of a specific channel, such as the for the current beta, I can't do https://api.dart.dev/beta/index.json as it redirects to the latest stable index page. I'd expect it to redirect to https://api.dart.dev/beta/3.3.0-174.3.beta/index.json

\cc @sortie

**Comment by sortie** [comment]
Like, I don't see any unit tests on this thing. It makes it risky to make changes especially since there's a production freeze going on.

**Comment by parlough** [comment]
> As such, I won't treat it as a super important breakage and delay fixing these problems to the new year. 

Thanks for checking in to this! No need to prioritize this then, even for the new year, I just wanted to make sure this was tracked.

> Like, I don't see any unit tests on this thing. It makes it risky to make changes especially since there's a production freeze going on.

Yeah it's part of the reason I didn't just open a PR right away...It's in a pretty confusing state.

Rather than trying to make improvements and fixes, I keep thinking to ignore a bunch of the legacy handling and switch to some Cloud Load Balancing + CDN setup which would come with a lot of other benefits (move away from soon to be discontinued python 2.7 app engine, brotli compression, http3 serving, etc). However, that's mostly impossible for me to setup outside of Google :/

**Comment by sortie** [comment]
I tried fixing this, but honestly, the lack of testing made it really difficult and the code is really hard to understand.

Meanwhile the Python 2.7 apocalypse is on us. We're currently working towards replacing the project entirely with a new implementation using modern technologies. For now, let's just live with these older bugs.

**Comment by parlough** [comment]
The Python 2.7 apocalypse. The less-scary follow up to the Javapocalypse of 2013 😆 

https://www.youtube.com/watch?v=E3418SeWZfQ

> We're currently working towards replacing the project entirely with a new implementation using modern technologies.

I think that makes a lot of sense and is definitely a better use of time. I'll keep this open so I don't forget to verify the behavior in the future, but feel free to close.

If you have a chance, I'd be curious what setup you're exploring?

**Comment by sortie** [comment]
Basically we're thinking of having a cloud load balancer cache the contents right out of the storage bucket. We'll have to deal with the redirect logic somehow, maybe by deprecating it, or serving html http equiv refresh tokens, or by duplicating files with multiple paths.

**Comment by athomas** [comment]
There's two ways to do that now in the new implementation:
https://api.dart.dev/stable/3.1.5 works now.
https://api.dart.dev/beta/index.json still doesn't work, but https://api.dart.dev/beta/latest/index.json does.
